
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import './fonts.css'
import Theme from "@/theme/Theme";
import { AppContextProvider } from "@/context/AppContext";
import { PrincipalContainer } from "@/components/Layout/Layout";
import { Box } from "@mui/material";
import SideMenuMobile from "@/components/sideMenu/SideMenuMobile";
import SideMenu from "@/components/sideMenu";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <Theme>

      <html lang="en">
        <AppContextProvider>
          <body className={inter.className}>

            <Box sx={{ display: { xs: 'static', md: 'flex' }, }} >
              <Box sx={{ display: { xs: 'none', md: 'flex' } }}>
                <SideMenu />
              </Box>
              <Box sx={{ display: { xs: 'flex', md: 'none' } }}>
                <SideMenuMobile />
              </Box>
              <PrincipalContainer>
                {children}
              </PrincipalContainer>
            </Box>
          </body>
        </AppContextProvider>
      </html>
    </Theme>

  );
}
